# Generated by Django 5.2.7 on 2025-10-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_gunung', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mountain',
            options={},
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='mountain',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='mountain',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='height_mdpl',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mountain',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
