# Generated by Django 5.2.7 on 2025-10-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_gunung', '0002_alter_mountain_options_remove_mountain_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
