# Generated by Django 5.1.11 on 2025-12-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_gunung', '0003_mountain_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='availability',
            field=models.BooleanField(default=True, help_text='Apakah gunung tersedia untuk booking'),
        ),
        migrations.AddField(
            model_name='mountain',
            name='experience_required',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', help_text='Level pengalaman minimum yang dibutuhkan', max_length=20),
        ),
        migrations.AddField(
            model_name='mountain',
            name='min_book',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah minimum orang per booking'),
        ),
    ]
