# Generated by Django 5.2.7 on 2025-10-22 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gunung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=100)),
                ('cuaca', models.CharField(max_length=50)),
                ('ketersediaan', models.BooleanField(default=True)),
                ('level_difficulty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax', models.IntegerField()),
                ('levels', models.JSONField()),
                ('porter_required', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gunung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.gunung')),
            ],
        ),
    ]
