# Generated by Django 5.2.7 on 2025-10-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='gunung',
        ),
        migrations.DeleteModel(
            name='Gunung',
        ),
    ]
