# Generated by Django 5.2.7 on 2025-10-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_gunung'),
        ('list_gunung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='gunung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list_gunung.mountain'),
        ),
    ]
