# Generated by Django 5.2.6 on 2025-12-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_climbing_date_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='climbing_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
