# Generated by Django 5.2.6 on 2025-12-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_climbing_end_date_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
