# Generated by Django 5.2.6 on 2025-10-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_gunung', '0001_initial'),
        ('userprofile', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='history_gunung',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history_gunung',
            field=models.ManyToManyField(blank=True, related_name='pendaki', to='list_gunung.mountain'),
        ),
    ]
